version: "3"
services:
    rabbitmq:
        image: rabbitmq:3.6.10-management-alpine
        environment:
            RABBITMQ_DEFAULT_USER: guest
            RABBITMQ_DEFAULT_PASS: guest
        ports:
            - 15672:15672

    nginx:
        build: ./nginx
        depends_on:
            - api
        ports:
            - 8080:8080
        volumes:
            - './public:/var/www/html'

    api:
        build: ./api
        depends_on:
            - rabbitmq
        command: >
            /bin/bash -c "
                while ! nc -z rabbitmq 15672;
                do
                echo sleeping;
                sleep 1;
                done;
                node .
            "
        environment:
            HTTP_PORT: 9080
            IMAGE_UPLOAD_PATH: "/opt/app/uploads"
            RABBIT_HOST: "rabbitmq"
            RABBIT_PORT: 15672
            IMAGE_SERVICE_QUEUE: "image-processing"
        ports:
            - 9080:9080
        volumes:
            - ./uploads:/opt/app/uploads
            - ./api:/opt/app

    worker:
        build: ./worker
        depends_on:
            - rabbitmq
        environment:
            WORKER_NAME: "Worker"
            IMAGE_UPLOAD_PATH: "/opt/app/uploads"
            IMAGE_SERVICE_QUEUE: "image-processing"
        volumes:
            - ./uploads:/opt/app/uploads
