rabbitmq:
    image: rabbitmq:3.6.10-management-alpine
    environment:
        RABBITMQ_DEFAULT_USER: guest
        RABBITMQ_DEFAULT_PASS: guest
    net: "container:nginx"    

nginx:
    build: ./nginx
    volumes:
        - './public:/var/www/html'
    ports:
        - 8080:8080
        - 9080:9080
        - 15672:15672

api:
    build: ./api
    environment:
        HTTP_PORT: 9080
        IMAGE_UPLOAD_PATH: "/opt/app/uploads"
        IMAGE_SERVICE_QUE: 'image-processing'
    volumes:
        - ./uploads:/opt/app/uploads
        - ./api:/opt/app
    net: "container:nginx"